version: '3.8'

services:
  backend:
    build: ./backend
    container_name: holistic_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app 
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/holistic_db
      - OLLAMA_API_URL=http://ollama:11434/api/generate 
    depends_on:
      db:
        condition: service_healthy
      ollama: 
        condition: service_started 
    networks:
      - holistic_network

  db:
    image: postgres:15-alpine
    container_name: holistic_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: holistic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d holistic_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - holistic_network

  ollama: 
    image: ollama/ollama:latest 
    container_name: holistic_ollama
    ports:
      - "11434:11434" 
    volumes:
      - ollama_data:/root/.ollama 
    # Dla wsparcia GPU (opcjonalne i bardziej złożone):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    networks:
      - holistic_network
    tty: true 
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data: 

networks:
  holistic_network:
    driver: bridge